### ISSUE TITLE
xml.etree.ElementTree.ParseError: junk after document element: line 157, column 0

### ISSUE THREAD

**Issue by drewwells** [simonkrenger/apple-health-to-fitbit#4] opened 2020-01-30 17:59 UTC
Seeing an error, I tried Python 3 and 2 but got similar errors. As pointed out in https://github.com/simonkrenger/apple-health-to-fitbit/issues/1 it's related to the parsing of ClinicalDocument closing tag

Python2
```
-> % /usr/bin/python ./health_to_fitbit.py   
Traceback (most recent call last):
  File "./health_to_fitbit.py", line 7, in <module>
    export_cda = ET.parse('export_cda.xml')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: junk after document element: line 157, column 0
```

```
-> % /usr/local/bin/python ./health_to_fitbit.py       
Traceback (most recent call last):
  File "./health_to_fitbit.py", line 7, in <module>
    export_cda = ET.parse('export_cda.xml')
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
    tree.parse(source, parser)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/etree/ElementTree.py", line 598, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: junk after document element: line 157, column 0
```

**Comment by simonkrenger** [comment] 2020-02-04 19:43
Thanks for bringing this to my attention.

I'll have to reproduce the issue on my side. Could you let me know which iOS version you are using?

Thanks.

**Comment by LangKenney** [comment] 2020-02-26 20:06
Getting the Same error. I'm on IOS 13.3.1.

**Comment by simonkrenger** [comment] 2020-02-27 10:36
@LangKenney Thanks for the update. As I cannot reproduce the issue on my side there is currently no resolution.

It would be very helpful if you could provide an anonymised version of your XML files so I can change the script to handle the additional data as well. In my Health.App exports, there is no additional data, but it could be that you have some additional data in your Health.App leading to the additional data.

> However, I can't find any .CSV output from it.
> Is it saving it somewhere special? I assumed it would be in the same folder?

The script generates output to STDOUT, so to the terminal. As noted in the README, you need to redirect the data yourself to a CSV file.

I hope that helps.

**Comment by simoneeva** [comment] 2020-04-23 08:56
Same error here, on iphone X ios13.4 jailbreaked.
If you need some files, or something else i'm glad to help!

**Comment by simonkrenger** [comment] 2020-04-23 10:41
@simoneeva It would be very helpful to have a look at the structure of your `export_cda.xml` file.

As this file contains personal and health-related information, please be mindful about sharing this information. So I would require you to remove all your personal and health-related information from the file but to keep the structure of the file intact. Please remove all but one of your `<component>` entries and provide the file either via this GitHub issue or via e-mail to simon@krenger.ch.

**Comment by simoneeva** [comment] 2020-04-23 10:58
Of course, i'll delete the personal info and send it right trought email.

I've got a question for you; i'm now trying to export the data on the iPhone with the QS app, and everything is fine, but i don't have any fitbit CVS to understand the syntax and follow as example for the import on Garmin Webapp.

Have you got one to share? it will be very helpful =)

**Comment by simonkrenger** [comment] 2020-04-23 15:27
@simoneeva Thank you, I received your data via e-mail and will have a look at your data.

There is an example in the `README.md` file of the repository, the CSV is quite simple and looks like this:
```
Body
Date,Weight,BMI,Fat
"01-01-2020","70.1","0","0"
"02-01-2020","70.3","0","0"
"03-01-2020","70.2","0","0"
[..]

Activities
Date,Calories Burned,Steps,Distance,Floors,Minutes Sedentary,Minutes Lightly Active,Minutes Fairly Active,Minutes Very Active,Activity Calories
"01-01-2020","0","61","0.01","0","0","0","0","0","0"
"02-01-2020","0","13,666","10.4","0","0","0","0","0","0"
"03-01-2020","0","6,901","5.78","0","0","0","0","0","0"
[..]
```

As you can see this only includes very basic information, so any other information is not contained in this CSV. In your case, with a lot of data (HR data, nutrition data, etc.) it might be worth checking if you can find any other way to import the data into Garmin Connect, as the way via the Fitbit CSV does not include a lot of data.

**Comment by simoneeva** [comment] 2020-04-23 16:12
Ah ok easy, it's the same as the readme.


I'll check ifis possible to import another types of data!

really thank you.

and if you need anything else from me, i'm here


regards

simone

Il 23/04/2020 17:27, Simon Krenger ha scritto:

**Comment by simonkrenger** [comment] 2020-04-24 17:37
Alright, so here is what I found. It turns out that the XML file contains multiple root nodes and the `export_cda.xml` looks like this:

```
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="CDA.xsl"?>
<ClinicalDocument ...>
 <entry typeCode="DRIV">
  <organizer ...>
   [..]
   <component>
     ... DATA HERE ...
   </component>
   <component>
     ... DATA HERE ...
   </component>
</ClinicalDocument>
<component>
 <section>
  <entry ...>
   <organizer ...>
    <component>
       ... DATA HERE ...
    </component>
[..]
   </organizer>
  </entry>
 </section>
</component>
```

A XML document with multiple root nodes is invalid, which is why we get the `xml.etree.ElementTree.ParseError: junk after document element` error. Note this is the same error we see in issue #1 . I am not sure how this can be generated and that is obviously tricky to parse correctly.

@simoneeva Can you confirm that you exported the data using the Apple Health app using "Profile" => "Export All Health Data" => "Export"?

**Comment by simoneeva** [comment] 2020-04-24 17:40
I can confirm it! Yes, and it creates the zip I sent to you

**Comment by simonkrenger** [comment] 2020-04-24 17:42
@simoneeva Thanks for the update. Interesting, thanks for the confirmation. I'll have to check how we can fix the data, as others seem the have the same issue...

**Comment by simonkrenger** [comment] 2020-04-29 18:12
@simoneeva I have just added a new `fix_invalid_export_cda_xml.py` file to the repository. Could you please download the latest versions of all the scripts and run it like so:

```
$ ls -la
total 3472248
drwxr-xr-x@  9 simon  staff        288 Apr 28 23:00 .
drwx------@ 13 simon  staff        416 Apr 29 11:39 ..
-rwxr-xr-x@  1 simon  staff       2318 Apr 23 17:30 convert_export-xml_to_csv.py
-rw-r--r--@  1 simon  staff  569828352 Apr 23 17:19 export.xml
-rw-r--r--@  1 simon  staff  602758060 Apr 29 20:11 export_cda.xml
-rwxr-xr-x   1 simon  staff       3400 Apr 29 20:08 fix_invalid_export_cda_xml.py
-rwxr-xr-x@  1 simon  staff       2895 Apr 28 23:01 health_to_fitbit.py
$ ./fix_invalid_export_cda_xml.py
Confirmed invalid XML (ParseError)
Are you sure you want to try to fix your export_cda.xml? This will overwrite your current export_cda.xml. Confirm with 'yes': yes
Processing 'export_cda.xml'...
Found end of ClinicalDocument.
Done processing.
Parsing the ClinicalDocument...
Parsing the rest of the document...
Done. Now merging the two parts into the ClinicalDocument...
Success
```

After that, you should be able to run the `health_to_fitbit.py` script as described in the README.

**Comment by simoneeva** [comment] 2020-05-01 10:15
really thank you!! this worked flawlessly!

thank you again =)

**Comment by simonkrenger** [comment] 2020-05-01 10:29
@simoneeva Glad to hear. I added an error message to the `health_to_fitbit` script so others can use the script as well: 97d2d4d

Closing this issue now.

**Closed by simonkrenger** 2020-05-01 10:29 UTC
Labels: bug
